export interface Concept {
    id: number;
    domain: 'CYBERSECURITY' | 'AI' | 'QUANTUM';
    title: string;
    explanation: string;
    analogy: string;
    question: string;
    options: [string, string, string];
    correctIndex: number;
    reinforcement: string;
}

export const concepts: Concept[] = [
    {
        id: 1,
        domain: 'CYBERSECURITY',
        title: 'What is a Packet?',
        explanation: 'Every piece of data you send or receive over the internet is broken into small chunks called packets. Each packet travels independently across the network, potentially taking different routes, and is reassembled at the destination. A single email might be broken into dozens of packets.',
        analogy: 'Think of it like sending a book through the mail by tearing out each page, putting each in its own envelope with the page number, and mailing them separately. The recipient puts them back in order.',
        question: 'Why is data split into packets rather than sent as one continuous block?',
        options: [
            'So multiple users can share the same network simultaneously',
            'Because computers can only process small amounts of data',
            'To make the data harder for attackers to read',
        ],
        correctIndex: 0,
        reinforcement: 'Packet switching allows millions of users to share network infrastructure efficiently. If one user sent a single continuous block, everyone else would have to wait.',
    },
    {
        id: 2,
        domain: 'AI',
        title: 'What Does a Neural Network Actually Do?',
        explanation: 'A neural network is a mathematical function that takes input data, passes it through layers of connected nodes (neurons), and produces an output. Each connection has a weight — a number that determines how much influence one node has on another. Training adjusts these weights until the outputs match the expected results.',
        analogy: 'Imagine a room of people passing notes. Each person reads the notes they receive, decides how important each one is (the weight), writes a summary, and passes it forward. After enough rounds of feedback, the final person consistently gives the right answer.',
        question: 'What happens during the "training" of a neural network?',
        options: [
            'The network memorises every example it has ever seen',
            'The connection weights are adjusted to reduce errors in output',
            'New neurons are added to increase the network's size',
        ],
        correctIndex: 1,
        reinforcement: 'Training is the process of adjusting weights. The network does not memorise — it generalises patterns from examples by minimising the difference between its output and the correct answer.',
    },
    {
        id: 3,
        domain: 'QUANTUM',
        title: 'What is a Qubit?',
        explanation: 'A classical bit is either 0 or 1. A quantum bit (qubit) can exist in a superposition of both states simultaneously. When you measure it, it collapses to one state — but before measurement, it holds more information than a classical bit. This property is what gives quantum computers their potential power for certain problems.',
        analogy: 'A coin on a table is heads or tails — that is a classical bit. A coin spinning in the air is in a superposition — it is both heads and tails until it lands. The qubit is the spinning coin.',
        question: 'What makes a qubit different from a classical bit?',
        options: [
            'It is faster at processing ones and zeros',
            'It can exist in a superposition of both 0 and 1 simultaneously',
            'It stores data permanently without power',
        ],
        correctIndex: 1,
        reinforcement: 'Superposition is the key difference. A qubit holds both states at once, enabling quantum computers to explore many possibilities simultaneously for certain types of calculations.',
    },
    {
        id: 4,
        domain: 'CYBERSECURITY',
        title: 'What is Encryption at Rest?',
        explanation: 'Encryption at rest means data is encrypted while stored on a device — a hard drive, a phone, a cloud server. Even if someone physically steals the device or gains unauthorised access to the storage, they cannot read the data without the encryption key. This is different from encryption in transit, which protects data while it moves across networks.',
        analogy: 'Think of it as locking your diary in a safe. Even if someone breaks into your house and takes the safe, they still cannot read what is inside without the combination.',
        question: 'When is "encryption at rest" protecting your data?',
        options: [
            'While data is being sent from your phone to a server',
            'While data is stored on a device or disk',
            'While you are actively viewing the data on screen',
        ],
        correctIndex: 1,
        reinforcement: 'At rest means while stored, not while moving. A full-disk encryption tool like BitLocker or FileVault protects everything on your drive even if the physical device is taken.',
    },
    {
        id: 5,
        domain: 'AI',
        title: 'What is a Hallucination in an LLM?',
        explanation: 'When a large language model generates text that sounds confident and plausible but is factually wrong, that is called a hallucination. The model is not lying — it has no concept of truth. It is generating the statistically most likely next words based on patterns in its training data, and sometimes those patterns produce nonsense that reads like fact.',
        analogy: 'Imagine someone who has read thousands of history books but never experienced any event. If asked about a battle that never happened, they might describe it convincingly using the patterns they learned from real battles. They are not deceiving — they are pattern-matching without grounding.',
        question: 'Why do language models sometimes generate false information confidently?',
        options: [
            'Because they predict likely word sequences, not verified facts',
            'Because their training data contains too many errors',
            'Because they are designed to agree with the user',
        ],
        correctIndex: 0,
        reinforcement: 'LLMs generate text by predicting what comes next based on probability. They have no verification mechanism — a plausible-sounding false claim and a true claim are equally producible if the patterns support them.',
    },
    {
        id: 6,
        domain: 'CYBERSECURITY',
        title: 'What is a Zero-Day?',
        explanation: 'A zero-day vulnerability is a software flaw that the vendor does not know about yet. The name comes from the fact that the developer has had zero days to fix it. When an attacker discovers and exploits a zero-day before anyone else knows it exists, the impact is severe because there is no patch, no workaround, no defence specifically designed for it.',
        analogy: 'Imagine a lock manufacturer ships millions of locks with a hidden flaw that allows a specific tool to open them. No one — not the manufacturer, not the owners — knows about this flaw. The first person to discover it can open any lock until the manufacturer finds out and issues a fix.',
        question: 'Why are zero-day vulnerabilities particularly dangerous?',
        options: [
            'They are the most technically complex attacks to execute',
            'There is no existing patch or specific defence when they are first exploited',
            'They can only be found by state-sponsored attackers',
        ],
        correctIndex: 1,
        reinforcement: 'The danger is the time gap. From the moment an attacker finds and uses a zero-day until the vendor discovers it, creates a patch, and users install it — every system with that flaw is exposed.',
    },
    {
        id: 7,
        domain: 'QUANTUM',
        title: 'Why Quantum Computers Are Not Just Faster Computers',
        explanation: 'Quantum computers are not faster versions of classical computers. They are fundamentally different machines that excel at specific types of problems — like factoring large numbers, simulating molecules, or optimising across many variables. For everyday tasks like browsing the web or editing a document, a quantum computer offers no advantage.',
        analogy: 'A submarine and a car are both vehicles. The submarine is not a "faster car" — it solves a completely different problem (moving underwater). Saying quantum computers are faster than classical ones is like saying submarines are faster than cars. They operate in different domains.',
        question: 'For which tasks are quantum computers expected to outperform classical ones?',
        options: [
            'Web browsing, email, and document editing',
            'Factoring large numbers and simulating molecular behaviour',
            'Every computational task if given enough qubits',
        ],
        correctIndex: 1,
        reinforcement: 'Quantum advantage exists for specific problem classes. Most everyday computing tasks gain nothing from quantum hardware. The power lies in problems with massive combinatorial complexity.',
    },
    {
        id: 8,
        domain: 'CYBERSECURITY',
        title: 'Why Passwords Fail',
        explanation: 'Passwords fail not because the concept is wrong but because humans are predictable. We reuse them, make them short, base them on personal information, and resist changing them. An attacker with a leaked password database can crack most human-chosen passwords in minutes using dictionary attacks and pattern matching.',
        analogy: 'A lock is only as good as its key. If everyone in a city uses the same three key patterns, a thief only needs three keys to open most doors. Password reuse is exactly that — millions of people using the same "keys" across different services.',
        question: 'What is the primary reason passwords fail as a security measure?',
        options: [
            'The encryption algorithms behind passwords are too weak',
            'Humans choose predictable passwords and reuse them across services',
            'Servers cannot store passwords securely',
        ],
        correctIndex: 1,
        reinforcement: 'The encryption is usually fine. The problem is human behaviour — predictable choices plus credential reuse means a single breach can compromise dozens of accounts.',
    },
    {
        id: 9,
        domain: 'AI',
        title: 'What is Transfer Learning?',
        explanation: 'Transfer learning is the practice of taking a model trained on one task and adapting it for a different but related task. Instead of training from scratch — which requires massive amounts of data and compute — you start with a model that already understands general patterns and fine-tune it for your specific problem.',
        analogy: 'A chef who has mastered French cooking does not start from zero when learning Italian cuisine. They already understand heat, timing, flavour balance, and knife skills. They transfer that foundation and learn only the Italian-specific techniques.',
        question: 'What is the main advantage of transfer learning?',
        options: [
            'It eliminates the need for any training data',
            'It allows you to build on existing knowledge rather than learning from scratch',
            'It makes models smaller and faster to run',
        ],
        correctIndex: 1,
        reinforcement: 'Transfer learning dramatically reduces the data and compute needed for new tasks. Models like GPT and BERT are pre-trained on massive datasets, then fine-tuned for specific applications with much less effort.',
    },
    {
        id: 10,
        domain: 'CYBERSECURITY',
        title: 'What is Two-Factor Authentication?',
        explanation: 'Two-factor authentication (2FA) requires two different types of verification: something you know (a password), something you have (a phone or hardware key), or something you are (a fingerprint). Even if an attacker steals your password, they cannot access your account without the second factor.',
        analogy: 'A bank vault requires both a key and a combination. Even if a thief steals the key, they still need the combination. 2FA applies this principle to digital accounts — possessing one credential is not enough.',
        question: 'If someone obtains your password, what prevents them from accessing a 2FA-protected account?',
        options: [
            'The account locks after one failed attempt',
            'They need a second verification factor they do not possess',
            'The password changes automatically every hour',
        ],
        correctIndex: 1,
        reinforcement: 'The strength of 2FA is that compromising one factor is not sufficient. An attacker needs both your password AND your phone (or hardware key or biometric) to gain access.',
    },
    {
        id: 11,
        domain: 'QUANTUM',
        title: 'What is Quantum Entanglement?',
        explanation: 'When two qubits become entangled, measuring one instantly determines the state of the other, regardless of the distance between them. This is not communication — no information travels between the qubits. But it is a correlation so deep that classical physics cannot explain it. Entanglement is a resource that quantum algorithms use to solve problems faster.',
        analogy: 'Imagine writing the same random number on two pieces of paper and sealing them in envelopes. You send one envelope to another continent. When someone opens their envelope and sees "7," they instantly know the other says "7" too. The information does not travel — it was correlated from the start. Entanglement is like this, but the "number" is not decided until someone opens an envelope.',
        question: 'Does quantum entanglement allow faster-than-light communication?',
        options: [
            'Yes, because the states are correlated instantly across distance',
            'No, because the correlation cannot be used to send a chosen message',
            'Only if both qubits are measured simultaneously',
        ],
        correctIndex: 1,
        reinforcement: 'Entanglement produces correlated outcomes, not controllable signals. You cannot choose what the measurement result will be, so you cannot encode a message in it. Einstein called it "spooky action at a distance," but it does not violate relativity.',
    },
    {
        id: 12,
        domain: 'AI',
        title: 'What is Overfitting?',
        explanation: 'Overfitting occurs when a machine learning model learns the training data too well — including its noise and outliers — and performs poorly on new, unseen data. The model has memorised rather than generalised. It is like a student who memorises test answers but cannot solve a slightly different problem.',
        analogy: 'A student who memorises every question and answer from past exams scores perfectly on those exams but fails when given new questions on the same subject. They learned the specific examples, not the underlying principles.',
        question: 'How can you tell if a model is overfitting?',
        options: [
            'It performs well on training data but poorly on new data',
            'It takes too long to train',
            'It produces the same output for every input',
        ],
        correctIndex: 0,
        reinforcement: 'The gap between training performance and real-world performance is the signal. High accuracy on training data but low accuracy on test data is the classic overfitting signature.',
    },
    {
        id: 13,
        domain: 'CYBERSECURITY',
        title: 'What is Social Engineering?',
        explanation: 'Social engineering is manipulating people into giving up confidential information or performing actions that compromise security. It exploits trust, urgency, authority, and curiosity rather than technical vulnerabilities. Most successful breaches involve social engineering at some stage — it is easier to trick a person than to break encryption.',
        analogy: 'A con artist does not pick locks. They knock on the door, claim to be from maintenance, and are let in by a trusting resident. Social engineering is the digital version — it targets the human, not the technology.',
        question: 'What makes social engineering effective against even well-secured organisations?',
        options: [
            'It exploits advanced vulnerabilities in security software',
            'It targets human psychology rather than technical defences',
            'It uses quantum computing to break encryption',
        ],
        correctIndex: 1,
        reinforcement: 'No amount of technical security can fully protect against a well-crafted social engineering attack, because it targets the one element that cannot be patched: human behaviour.',
    },
    {
        id: 14,
        domain: 'AI',
        title: 'What is Reinforcement Learning?',
        explanation: 'Reinforcement learning is a type of machine learning where an agent learns by interacting with an environment. It takes actions, receives rewards or penalties, and adjusts its strategy to maximise cumulative reward over time. No labelled training data is provided — the agent discovers what works through trial and error.',
        analogy: 'A child learning to ride a bicycle does not study a textbook. They try, fall, adjust their balance, try again, and eventually ride smoothly. The reward is staying upright; the penalty is falling. The child is a reinforcement learning agent.',
        question: 'How does reinforcement learning differ from supervised learning?',
        options: [
            'It uses labelled datasets with correct answers provided',
            'It learns through trial and error with rewards and penalties',
            'It requires less computational power',
        ],
        correctIndex: 1,
        reinforcement: 'In supervised learning, the correct answer is given. In reinforcement learning, the agent must discover the correct behaviour through experimentation and feedback, which makes it suited for problems like game-playing and robotics.',
    },
    {
        id: 15,
        domain: 'QUANTUM',
        title: 'What is Post-Quantum Cryptography?',
        explanation: 'Post-quantum cryptography refers to cryptographic algorithms designed to be secure against both classical and quantum computers. Current public-key systems like RSA and ECC will be breakable by sufficiently powerful quantum computers. Post-quantum algorithms use mathematical problems that remain hard even for quantum machines — like lattice-based problems.',
        analogy: 'If you discover that a new type of saw can cut through steel locks, you do not abandon locks — you build locks from a material the new saw cannot cut. Post-quantum cryptography is building those locks before the saw arrives.',
        question: 'Why is post-quantum cryptography being developed now, before large quantum computers exist?',
        options: [
            'Because current encryption is already broken',
            'Because encrypted data captured today could be decrypted in the future',
            'Because quantum computers are already widely available',
        ],
        correctIndex: 1,
        reinforcement: 'The "harvest now, decrypt later" threat means adversaries can store encrypted communications today and decrypt them once quantum computers mature. Transitioning cryptography takes years, so the work must begin now.',
    },
    {
        id: 16,
        domain: 'CYBERSECURITY',
        title: 'What is a Firewall?',
        explanation: 'A firewall is a security system that monitors and controls incoming and outgoing network traffic based on predetermined rules. It acts as a barrier between a trusted internal network and untrusted external networks. Firewalls can be hardware devices, software programs, or both. They inspect packets and decide whether to allow or block them.',
        analogy: 'A firewall is like a security guard at a building entrance. They check every person's ID against a list of who is allowed in and who is not.Some guards are strict(block everything not explicitly allowed), others are permissive(allow everything not explicitly blocked).',
    question: 'What does a firewall primarily do?',
        options: [
            'Encrypts all data leaving the network',
            'Filters network traffic based on predefined security rules',
            'Scans files for viruses before downloading them',
        ],
        correctIndex: 1,
        reinforcement: 'Firewalls are traffic controllers, not scanners or encryptors. They evaluate each packet against rules and make an allow/deny decision. They are a first line of defence, not a complete security solution.',
    },
    {
        id: 17,
        domain: 'AI',
        title: 'What is Bias in AI?',
        explanation: 'AI bias occurs when a model systematically produces unfair results because of assumptions in the training data or the algorithm design. If a hiring model is trained on historical data where certain groups were under-represented, it may learn to replicate that pattern. Bias is not always intentional — it is often inherited from the world the data describes.',
        analogy: 'If you train a dog to fetch only red balls by only ever throwing red balls, it will ignore blue balls — not because blue balls are wrong, but because its training never included them. AI bias works similarly: the model reflects what it was shown, including the gaps.',
        question: 'Where does AI bias most commonly originate?',
        options: [
            'From deliberate programming by developers',
            'From imbalances and assumptions in the training data',
            'From the hardware the model runs on',
        ],
        correctIndex: 1,
        reinforcement: 'Most AI bias is inherited, not designed. If training data over-represents one group or under-represents another, the model learns those patterns as "normal" and reproduces them in its outputs.',
    },
    {
        id: 18,
        domain: 'CYBERSECURITY',
        title: 'What is a VPN?',
        explanation: 'A Virtual Private Network creates an encrypted tunnel between your device and a server, hiding your internet traffic from anyone watching the connection — your ISP, the Wi-Fi operator, or a network-level attacker. Your traffic appears to originate from the VPN server, not from your actual location. A VPN provides privacy in transit, not anonymity.',
        analogy: 'Imagine sending all your mail through a private courier service that puts your letters inside their own sealed envelopes, delivers them from their address, and returns responses the same way. Your neighbours see you sending packages to the courier, but they cannot see what is inside or where it ultimately goes.',
        question: 'What does a VPN NOT do?',
        options: [
            'Encrypt your traffic between your device and the VPN server',
            'Guarantee complete anonymity online',
            'Hide your traffic from your local network operator',
        ],
        correctIndex: 1,
        reinforcement: 'A VPN provides encryption and IP masking, but it does not guarantee anonymity. The VPN provider can see your traffic, websites can still track you through cookies and fingerprinting, and your behaviour patterns can still identify you.',
    },
    {
        id: 19,
        domain: 'QUANTUM',
        title: 'What is Quantum Supremacy?',
        explanation: 'Quantum supremacy (or quantum advantage) is the point at which a quantum computer performs a specific task that no classical computer can complete in a reasonable time. Google claimed this milestone in 2019 with a calculation their quantum processor completed in 200 seconds that would take a classical supercomputer thousands of years. The debate continues about whether the classical estimate was accurate.',
        analogy: 'If classical computers are runners and quantum computers are swimmers, quantum supremacy is the moment a swimmer completes an ocean crossing faster than a runner could — not because swimming is universally faster, but because the ocean is the right terrain for it.',
        question: 'Does quantum supremacy mean quantum computers are better than classical computers at everything?',
        options: [
            'Yes, once achieved it applies to all types of computation',
            'No, it refers to advantage on specific problem types only',
            'It depends on the number of qubits available',
        ],
        correctIndex: 1,
        reinforcement: 'Quantum supremacy is task-specific. The 2019 Google experiment solved a very particular sampling problem. For most practical computing, classical machines remain more efficient, reliable, and cost-effective.',
    },
    {
        id: 20,
        domain: 'AI',
        title: 'What is a Large Language Model?',
        explanation: 'A large language model (LLM) is a neural network trained on vast amounts of text data to predict the next word in a sequence. By scaling this simple objective to billions of parameters and trillions of words of training data, LLMs develop emergent abilities: they can summarise, translate, write code, answer questions, and reason — all from next-word prediction.',
        analogy: 'Imagine someone who has read every book, article, and conversation ever written. They do not understand what they read — but they are extraordinarily good at predicting what comes next in any sentence. That predictive ability, at scale, produces behaviour that looks like understanding.',
        question: 'What is the core training objective of most LLMs?',
        options: [
            'Understanding the meaning behind every sentence',
            'Predicting the next word in a sequence of text',
            'Storing and retrieving factual information accurately',
        ],
        correctIndex: 1,
        reinforcement: 'Next-word prediction is the foundation. Understanding is not the objective — it is an emergent property that appears at sufficient scale. This is why LLMs can be confidently wrong: they predict plausible words, not verified facts.',
    },
    {
        id: 21,
        domain: 'CYBERSECURITY',
        title: 'What is Phishing?',
        explanation: 'Phishing is a social engineering attack where an attacker sends a message — usually email — that impersonates a trusted entity to trick the recipient into revealing credentials, clicking a malicious link, or downloading malware. It remains the most common initial attack vector for data breaches. Sophisticated phishing (spear phishing) targets specific individuals with personalised content.',
        analogy: 'A phishing email is a forged letter on bank letterhead, sent to your home, asking you to "verify your account" by filling in your details and mailing them back. The letter looks official. The address it goes to is not the bank.',
        question: 'What distinguishes spear phishing from regular phishing?',
        options: [
            'It uses more advanced encryption techniques',
            'It is personalised and targeted at specific individuals',
            'It only works on mobile devices',
        ],
        correctIndex: 1,
        reinforcement: 'Regular phishing casts a wide net with generic messages. Spear phishing researches the target — using their name, company, role, recent activity — making the deception far more convincing and harder to detect.',
    },
    {
        id: 22,
        domain: 'QUANTUM',
        title: "What is Shor's Algorithm?",
        explanation: "Shor's algorithm is a quantum algorithm that can factor large numbers exponentially faster than any known classical algorithm. This matters because RSA encryption — used to secure most internet communications — relies on the assumption that factoring large numbers is practically impossible. A sufficiently powerful quantum computer running Shor's algorithm could break RSA.",
        analogy: "Imagine a combination lock with a trillion possible combinations. A classical approach tries them one by one. Shor's algorithm is like having a tool that can test many combinations simultaneously, finding the right one in minutes instead of millennia.",
        question: "Why does Shor's algorithm threaten current encryption standards?",
        options: [
            'It can guess any password in seconds',
            'It efficiently factors the large numbers that RSA security depends on',
            'It breaks symmetric encryption like AES-256',
        ],
        correctIndex: 1,
        reinforcement: "RSA's security rests on the difficulty of factoring large numbers. Shor's algorithm solves this efficiently on a quantum computer. Note: it does NOT threaten symmetric encryption (AES) or hash functions — only public-key systems based on factoring and discrete logarithms.",
    },
    {
        id: 23,
        domain: 'AI',
        title: 'What is Computer Vision?',
        explanation: 'Computer vision is the field of AI that enables machines to interpret and understand visual information from the world — images, videos, and real-time camera feeds. Modern computer vision uses deep learning (specifically convolutional neural networks) to recognise objects, faces, text, and scenes with accuracy that sometimes exceeds human performance.',
        analogy: 'Teaching a computer to see is like teaching someone to read by showing them millions of examples of each letter until they can recognise any handwriting. Computer vision models learn visual patterns the same way — through massive exposure to labelled images.',
        question: 'What type of neural network is most commonly used for computer vision tasks?',
        options: [
            'Recurrent Neural Networks (RNNs)',
            'Convolutional Neural Networks (CNNs)',
            'Generative Adversarial Networks (GANs)',
        ],
        correctIndex: 1,
        reinforcement: 'CNNs are designed specifically for visual data. They use filters that scan across images to detect features — edges, textures, shapes — building increasingly abstract representations through deeper layers.',
    },
    {
        id: 24,
        domain: 'CYBERSECURITY',
        title: 'What is Ransomware?',
        explanation: 'Ransomware is malware that encrypts a victim's files and demands payment for the decryption key.Modern ransomware often uses double extortion — encrypting data AND threatening to publish it.It typically spreads through phishing emails, compromised websites, or exploited vulnerabilities.Paying the ransom does not guarantee data recovery.',
    analogy: 'Someone breaks into your house, puts all your belongings in safes with locks only they have the keys to, and leaves a note demanding payment. Even if you pay, there is no guarantee they will actually give you the keys — and they might come back.',
        question: 'Why do security experts generally advise against paying ransomware demands?',
        options: [
            'Because the payment methods are too complicated',
            'Because payment does not guarantee data recovery and funds further attacks',
            'Because the encrypted data is automatically recoverable after 30 days',
        ],
        correctIndex: 1,
        reinforcement: 'Paying incentivises more attacks, funds criminal organisations, and does not guarantee decryption. The recommended approach is to maintain offline backups, patch systems, and train users to recognise phishing — prevention over payment.',
    },
    {
        id: 25,
        domain: 'AI',
        title: 'What is Natural Language Processing?',
        explanation: 'Natural Language Processing (NLP) is the branch of AI focused on enabling computers to understand, interpret, and generate human language. It powers chatbots, translators, sentiment analysis, voice assistants, and search engines. Modern NLP uses transformer architectures and large language models to achieve remarkably human-like text understanding.',
        analogy: 'Teaching a computer human language is like teaching a foreigner to understand not just dictionary definitions but sarcasm, context, cultural references, and implied meaning. NLP is the entire journey from "what do these words mean" to "what does this person actually want."',
        question: 'Which architecture breakthrough most significantly advanced NLP in recent years?',
        options: [
            'The Transformer architecture',
            'The Perceptron model',
            'Decision Tree algorithms',
        ],
        correctIndex: 0,
        reinforcement: 'The Transformer, introduced in 2017 ("Attention Is All You Need"), revolutionised NLP by allowing models to process entire sequences in parallel rather than word-by-word, enabling the training of much larger and more capable language models.',
    },
    {
        id: 26,
        domain: 'CYBERSECURITY',
        title: 'What is the CIA Triad?',
        explanation: 'The CIA Triad — Confidentiality, Integrity, and Availability — is the foundational model for information security. Confidentiality ensures only authorised people access data. Integrity ensures data has not been tampered with. Availability ensures systems and data are accessible when needed. Every security control maps back to one or more of these three principles.',
        analogy: 'Think of a hospital patient record. Confidentiality: only doctors and the patient can read it. Integrity: no one has altered the blood test results. Availability: the record is accessible when the doctor needs it at 3am in an emergency.',
        question: 'If an attacker defaces a website without stealing data or taking it offline, which CIA principle is primarily violated?',
        options: [
            'Confidentiality',
            'Integrity',
            'Availability',
        ],
        correctIndex: 1,
        reinforcement: 'A website defacement is a modification of data — the page content has been changed without authorisation. That is an integrity violation. The data was not stolen (no confidentiality breach) and the site remained accessible (no availability breach).',
    },
    {
        id: 27,
        domain: 'QUANTUM',
        title: 'What Are Quantum Gates?',
        explanation: 'Quantum gates are the basic operations performed on qubits — the quantum equivalent of classical logic gates (AND, OR, NOT). They manipulate qubits by rotating their quantum states. A Hadamard gate puts a qubit into superposition. A CNOT gate entangles two qubits. Quantum algorithms are sequences of these gates applied to qubits.',
        analogy: 'Classical logic gates are like switches that flip bits between 0 and 1. Quantum gates are like precise rotations of a spinning top — they do not just flip the state, they tilt it to any angle, creating the rich probabilistic states that quantum computing exploits.',
        question: 'What does a Hadamard gate do to a qubit?',
        options: [
            'Destroys the qubit and creates a new one',
            'Puts the qubit into an equal superposition of 0 and 1',
            'Measures the qubit and collapses its state',
        ],
        correctIndex: 1,
        reinforcement: 'The Hadamard gate is the most fundamental quantum operation. It transforms a qubit from a definite state (|0⟩ or |1⟩) into an equal superposition of both, which is the starting point for many quantum algorithms.',
    },
    {
        id: 28,
        domain: 'CYBERSECURITY',
        title: 'What is a Threat Actor?',
        explanation: 'A threat actor is any entity — individual, group, or organisation — that poses a threat to cybersecurity. They range from script kiddies (using pre-made tools) to advanced persistent threats (APTs, often state-sponsored). Understanding threat actors matters because your defence strategy should match the type of adversary you face.',
        analogy: 'In home security, a teenager trying doorknobs is a different threat than a professional burglar with specialised tools. You would not install a vault door to stop the teenager, and you would not rely on a chain lock against the professional. Knowing your adversary determines your response.',
        question: 'What characterises an Advanced Persistent Threat (APT)?',
        options: [
            'They use automated scanning tools found on the internet',
            'They are well-funded, persistent, and often state-sponsored with specific objectives',
            'They only target financial institutions',
        ],
        correctIndex: 1,
        reinforcement: 'APTs are distinguished by resources, persistence, and specificity. They target particular organisations for strategic reasons (espionage, sabotage) and maintain long-term access rather than seeking quick financial gain.',
    },
    {
        id: 29,
        domain: 'AI',
        title: 'What is an AI Agent?',
        explanation: 'An AI agent is a system that can perceive its environment, make decisions, and take actions to achieve goals — autonomously. Unlike a chatbot that responds to prompts, an agent plans, uses tools, handles errors, and adjusts its strategy. Modern AI agents combine LLMs with code execution, web browsing, file manipulation, and API calls.',
        analogy: 'A chatbot is like a reference librarian who answers questions when asked. An AI agent is like a research assistant who takes your question, searches multiple sources, writes a draft, revises it based on what they find, and delivers a finished report — without you directing each step.',
        question: 'What distinguishes an AI agent from a standard chatbot?',
        options: [
            'Agents use more parameters in their language model',
            'Agents can autonomously plan, use tools, and take goal-directed actions',
            'Agents are always connected to the internet',
        ],
        correctIndex: 1,
        reinforcement: 'Agency is defined by autonomy and tool use. An agent does not just respond — it decides what to do next, executes actions, evaluates results, and adjusts its approach to achieve a stated goal.',
    },
    {
        id: 30,
        domain: 'QUANTUM',
        title: 'What is Quantum Key Distribution?',
        explanation: 'Quantum Key Distribution (QKD) uses quantum mechanics to securely share encryption keys. It exploits a fundamental property: measuring a quantum state disturbs it. If an eavesdropper intercepts the quantum signals used to create the key, the disturbance is detectable, and the key exchange is aborted. QKD provides information-theoretic security — its security is based on physics, not computational assumptions.',
        analogy: 'Imagine sending a message written on soap bubbles. If anyone tries to read it in transit, the bubbles pop and the message is destroyed. Both the sender and receiver know the message was intercepted because the bubbles never arrive intact. QKD works on this principle — observation changes the quantum state.',
        question: 'How does QKD detect eavesdropping?',
        options: [
            'By using mathematically unbreakable encryption algorithms',
            'By detecting disturbances in quantum states caused by measurement',
            'By encrypting the key with another key before sending it',
        ],
        correctIndex: 1,
        reinforcement: 'The Heisenberg uncertainty principle guarantees that measuring quantum states changes them. QKD exploits this: if error rates in the key exchange exceed a threshold, both parties know an eavesdropper was present and discard the key.',
    },
];
