export type GameStatus = 'live' | 'daily' | 'coming-soon';

export interface Game {
    id: string;
    index: string;
    name: string;
    tagline: string;
    tags: string[];
    description: string;
    status: GameStatus;
    statusLabel: string;
    frequency: 'daily' | 'on-demand' | 'once';
    cta: string;
    href: string;
    accentColor: string;
    hoverBg: string;
    meta: string[];
}

export const TAG_OPTIONS = [
    'ALL',
    'CYBERSECURITY',
    'AI',
    'QUANTUM',
    'DAILY',
    'AWARENESS',
    'SELF-GROWTH',
    'LEARNING',
    'CHALLENGE',
] as const;

export const games: Game[] = [
    {
        id: 'signal-or-noise',
        index: '01',
        name: 'Signal or Noise',
        tagline: 'Every piece of information is trying to tell you something. Most of it is lying.',
        tags: ['CYBERSECURITY', 'AI', 'AWARENESS', 'DAILY'],
        description: 'Five items a day — headlines, emails, posts, statistics. Determine which are real signals and which are noise. Covers phishing, social engineering, AI-generated content, and statistical manipulation.',
        status: 'daily',
        statusLabel: 'DAILY',
        frequency: 'daily',
        cta: 'READ TODAY\'S FEED →',
        href: '/resources/games/signal-or-noise',
        accentColor: '#EDF0FF',
        hoverBg: 'rgba(237, 240, 255, 0.02)',
        meta: ['5 ITEMS', 'STREAK TRACKED', '~5 MIN'],
    },
    {
        id: 'the-breach',
        index: '02',
        name: 'The Breach',
        tagline: 'Something got in. Walk back through it.',
        tags: ['CYBERSECURITY', 'LEARNING', 'CHALLENGE'],
        description: 'Post-incident report reconstruction. Drag-and-drop attack timeline building with MITRE ATT&CK technique identification. Multiple scenarios in rotation.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'RECONSTRUCT THE BREACH →',
        href: '/resources/games/the-breach',
        accentColor: '#E05C20',
        hoverBg: 'rgba(224, 92, 32, 0.025)',
        meta: ['10 EVENTS', 'DRAG-AND-DROP', '~15 MIN'],
    },
    {
        id: 'mirror',
        index: '03',
        name: 'Mirror',
        tagline: 'The AI is generating. So are you. Only one of you knows what it means.',
        tags: ['AI', 'AWARENESS', 'LEARNING', 'CHALLENGE'],
        description: 'Pairs of text — one human, one AI. Identify which is which, explain your reasoning, and build an understanding of how you detect AI-generated content.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'START COMPARING →',
        href: '/resources/games/mirror',
        accentColor: '#1A8FE3',
        hoverBg: 'rgba(26, 143, 227, 0.025)',
        meta: ['5 PAIRS', 'REASON TRACKING', '~8 MIN'],
    },
    {
        id: 'speech-of-the-day',
        index: '04',
        name: 'Speech of the Day',
        tagline: 'Read it. Understand it. Say it out loud. Then it\'s yours.',
        tags: ['AI', 'CYBERSECURITY', 'QUANTUM', 'SELF-GROWTH', 'DAILY'],
        description: 'A 90-150 word script on a concept from cybersecurity, AI, or quantum. Read it, understand it, record yourself saying it. The recording stays entirely local.',
        status: 'daily',
        statusLabel: 'DAILY',
        frequency: 'daily',
        cta: 'TODAY\'S SCRIPT →',
        href: '/resources/games/speech-of-the-day',
        accentColor: '#18C96A',
        hoverBg: 'rgba(24, 201, 106, 0.02)',
        meta: ['~150 WORDS', 'LOCAL RECORDING', '~5 MIN'],
    },
    {
        id: 'quantum-question',
        index: '05',
        name: 'Quantum Question',
        tagline: 'Quantum computing doesn\'t break everything. It breaks specific things. Know which ones.',
        tags: ['QUANTUM', 'AWARENESS', 'LEARNING'],
        description: 'Scenario-based MCQ correcting myths about quantum computing. What it can do, what it cannot, which algorithms are vulnerable, and current timeline estimates.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'TEST YOUR ASSUMPTIONS →',
        href: '/resources/games/quantum-question',
        accentColor: '#A78FFF',
        hoverBg: 'rgba(167, 143, 255, 0.025)',
        meta: ['6 SCENARIOS', '45S TIMER', '~10 MIN'],
    },
    {
        id: 'threat-profile',
        index: '06',
        name: 'Threat Profile',
        tagline: 'You\'ve seen the attack. Now build the file on who did it.',
        tags: ['CYBERSECURITY', 'AI', 'LEARNING', 'CHALLENGE'],
        description: 'Build a threat actor profile from an incident brief. Fill structured fields — motivation, capability tier, TTPs, target sectors — and compare against the expert assessment.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'OPEN THE BRIEF →',
        href: '/resources/games/threat-profile',
        accentColor: '#E05C20',
        hoverBg: 'rgba(224, 92, 32, 0.025)',
        meta: ['STRUCTURED FORM', 'EXPERT SCORING', '~12 MIN'],
    },
    {
        id: 'decision-tree',
        index: '07',
        name: 'Decision Tree',
        tagline: 'Every decision has a cost. Most people never see it until it\'s too late.',
        tags: ['AI', 'CYBERSECURITY', 'AWARENESS', 'SELF-GROWTH'],
        description: 'Branching scenario game. Play as different professionals facing decisions with incomplete information. See how individually reasonable choices compound into outcomes.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'MAKE THE FIRST CALL →',
        href: '/resources/games/decision-tree',
        accentColor: '#EDF0FF',
        hoverBg: 'rgba(237, 240, 255, 0.02)',
        meta: ['5-7 DECISIONS', 'SVG TREE VIS', '~8 MIN'],
    },
    {
        id: 'cipher',
        index: '08',
        name: 'Cipher',
        tagline: 'Encryption is not a wall. It\'s a language. Learn to read it.',
        tags: ['CYBERSECURITY', 'QUANTUM', 'LEARNING', 'CHALLENGE'],
        description: 'Four progressive levels teaching cryptography through puzzles. Caesar cipher, substitution cipher, conceptual RSA, and why quantum breaks it.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'START WITH LEVEL 1 →',
        href: '/resources/games/cipher',
        accentColor: '#A78FFF',
        hoverBg: 'rgba(167, 143, 255, 0.025)',
        meta: ['4 LEVELS', 'PROGRESS SAVED', '~20 MIN'],
    },
    {
        id: 'the-audit',
        index: '09',
        name: 'The Audit',
        tagline: 'Your digital life has vulnerabilities. Find them before someone else does.',
        tags: ['CYBERSECURITY', 'AI', 'SELF-GROWTH', 'AWARENESS'],
        description: 'Structured self-assessment across six domains: passwords, devices, accounts, communications, data, habits. Produces a risk profile with specific fix instructions.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'once',
        cta: 'AUDIT YOUR DIGITAL LIFE →',
        href: '/resources/games/the-audit',
        accentColor: '#18C96A',
        hoverBg: 'rgba(24, 201, 106, 0.02)',
        meta: ['36 QUESTIONS', 'RADAR CHART', '~10 MIN'],
    },
    {
        id: 'one-concept-a-day',
        index: '10',
        name: 'One Concept a Day',
        tagline: 'Three minutes. One idea. One question. Come back tomorrow.',
        tags: ['AI', 'QUANTUM', 'CYBERSECURITY', 'LEARNING', 'DAILY'],
        description: 'A single concept explained in under 200 words with one analogy, one example, and one question. The value is compound learning — 365 building blocks across three domains.',
        status: 'daily',
        statusLabel: 'DAILY',
        frequency: 'daily',
        cta: 'TODAY\'S CONCEPT →',
        href: '/resources/games/one-concept-a-day',
        accentColor: '#1A8FE3',
        hoverBg: 'rgba(26, 143, 227, 0.025)',
        meta: ['~200 WORDS', '1 QUESTION', '~3 MIN'],
    },
    {
        id: 'build-a-threat-model',
        index: '11',
        name: 'Build a Threat Model',
        tagline: 'What are you protecting? From whom? How likely is each attack? Start thinking like a defender.',
        tags: ['CYBERSECURITY', 'AI', 'LEARNING', 'SELF-GROWTH'],
        description: 'Five-step guided wizard to create a real threat model for something you own. Uses simplified STRIDE methodology. Produces a downloadable, structured output.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'DEFINE YOUR ASSET →',
        href: '/resources/games/build-a-threat-model',
        accentColor: '#E05C20',
        hoverBg: 'rgba(224, 92, 32, 0.025)',
        meta: ['5-STEP WIZARD', 'EXPORTABLE', '~15 MIN'],
    },
    {
        id: 'reflection-log',
        index: '12',
        name: 'Reflection Log',
        tagline: 'Three questions. No wrong answers. Just honesty.',
        tags: ['SELF-GROWTH', 'DAILY'],
        description: 'Three prompts per day, drawn from a bank of 90. Write your answers, read past entries, delete any entry. Nothing leaves your device.',
        status: 'daily',
        statusLabel: 'DAILY',
        frequency: 'daily',
        cta: 'TODAY\'S QUESTIONS →',
        href: '/resources/games/reflection-log',
        accentColor: '#18C96A',
        hoverBg: 'rgba(24, 201, 106, 0.02)',
        meta: ['3 PROMPTS', 'JOURNAL HISTORY', '~5 MIN'],
    },
    {
        id: 'the-board',
        index: '13',
        name: 'The Board',
        tagline: 'You and the adversary are both rational. So why does the attacker usually win?',
        tags: ['CYBERSECURITY', 'AI', 'LEARNING', 'CHALLENGE'],
        description: 'Game theory simulation. Play as the defender with a budget and controls. The attacker\'s strategy is hidden — you see only outcomes. After five rounds, the strategy is revealed.',
        status: 'live',
        statusLabel: 'LIVE',
        frequency: 'on-demand',
        cta: 'SEE THE BOARD →',
        href: '/resources/games/the-board',
        accentColor: '#EDF0FF',
        hoverBg: 'rgba(237, 240, 255, 0.02)',
        meta: ['5 ROUNDS', '3 SCENARIOS', '~12 MIN'],
    },
    {
        id: 'system-check',
        index: '14',
        name: 'System Check',
        tagline: 'Not what you know. What you actually do. There\'s a difference.',
        tags: ['AI', 'CYBERSECURITY', 'QUANTUM', 'SELF-GROWTH', 'DAILY'],
        description: 'Daily accountability check-in across five dimensions: learned, applied, avoided, confused by, and want to understand. Surfaces patterns in your responses over time.',
        status: 'daily',
        statusLabel: 'DAILY',
        frequency: 'daily',
        cta: 'RUN TODAY\'S CHECK →',
        href: '/resources/games/system-check',
        accentColor: '#18C96A',
        hoverBg: 'rgba(24, 201, 106, 0.02)',
        meta: ['5 PROMPTS', 'PATTERN DETECTION', '~5 MIN'],
    },
];
